# Generated by Django 6.0.4 on 2026-04-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignevents',
            name='score_impact',
            field=models.IntegerField(default=0),
        ),
    ]
