# Generated by Django 6.0.4 on 2026-04-22 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0007_alter_campaignemails_campaign_and_more"),
        ("events", "0002_campaignevents_score_impact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignevents",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="campaigns.Campaigns",
            ),
        ),
        migrations.AlterField(
            model_name="campaignevents",
            name="campaign_email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="campaigns.campaignemails",
            ),
        ),
        migrations.AlterModelTable(
            name="campaignevents",
            table="campaign_events",
        ),
    ]
