# Generated by Django 6.0.4 on 2026-04-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaignevents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignevents',
            old_name='campaign_email_id',
            new_name='campaign_email',
        ),
    ]
