# Generated by Django 6.0.4 on 2026-04-21 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_rename_campaign_email_id_campaignevents_campaign_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampaignEvents',
        ),
    ]
