# Generated by Django 6.0.4 on 2026-04-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_delete_campaignevents"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="campaigns",
            table="campaigns",
        ),
    ]
