# Generated by Django 6.0.4 on 2026-04-22 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0006_alter_campaign_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignemails",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="campaigns.Campaigns",
            ),
        ),
        migrations.AlterModelTable(
            name="campaignemails",
            table="campaign_emails",
        ),
    ]
