# Generated by Django 6.0.4 on 2026-04-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("it_security", "IT Security"),
                    ("engineering", "Engineering"),
                    ("marketing", "Marketing"),
                    ("human_resources", "Human Resources"),
                    ("finance", "Finance"),
                    ("executive", "Executive"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="security_score",
            field=models.IntegerField(default=0),
        ),
    ]
