# Generated by Django 6.0.4 on 2026-04-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_department_user_security_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
