# Generated by Django 6.0.4 on 2026-04-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_forgot_password_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="forgot_password_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
