# Generated by Django 6.0.4 on 2026-04-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_forgot_password_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
