# Generated by Django 6.0.4 on 2026-04-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medias',
            name='bucket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medias',
            name='storage_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
