# Generated by Django 6.0.4 on 2026-04-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0002_alter_medias_bucket_alter_medias_storage_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='medias',
            name='upload_type',
            field=models.CharField(default='profile_image', max_length=50),
            preserve_default=False,
        ),
    ]
